stages:
  - build
  - deploy
image: docker:stable
services:
  - docker:dind
variables:
  DOCKER_DRIVER: overlay2

build-al9:
  image: $CI_REGISTRY/ndmspc/user/al9:dep
  stage: build
  script: scripts/make.sh release test
  except:
    - main
    - tags

build-rpm-copr:
  stage: deploy
  image:
    name: $CI_REGISTRY/ndmspc/user/al9:dep
  script:
    - export COPR_LOGIN COPR_TOKEN COPR_USER
    - scripts/copr.sh $COPR_DEBUG
    - export MY_PROJECT_VER=${CI_COMMIT_REF_NAME/v/}
    - export MY_VER_RELEASE=$(echo $MY_PROJECT_VER | cut -sd '-' -f2)
    - scripts/make.sh rpm
    - if [ -z "$MY_VER_RELEASE" ];then copr-cli build ndmspc/stable build/SRPMS/*.src.rpm --nowait; fi
    - if [ -n "$MY_VER_RELEASE" ];then copr-cli build ndmspc/testing build/SRPMS/*.src.rpm --nowait; fi
  only:
    - tags

prod-image:
  stage: deploy
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker pull $CI_REGISTRY_IMAGE:latest || true
    - export MY_PROJECT_VER=${CI_COMMIT_REF_NAME/v/}
    - export MY_VER_RELEASE=$(echo $MY_PROJECT_VER | cut -sd '-' -f2)
    - docker build --build-arg MY_PROJECT_VER="$MY_PROJECT_VER" --cache-from $CI_REGISTRY_IMAGE:latest --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME --tag $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
    # - if [ "$CI_COMMIT_REF_NAME" == "main" ]; then docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA; fi
    - if [ -z "$MY_VER_RELEASE" ];then docker push $CI_REGISTRY_IMAGE:latest; fi
  allow_failure: true
  # when: manual
  only:
    - tags
    # - main
