stages:
  - build
  - deploy

image: quay.io/podman/stable
variables:
  STORAGE_DRIVER: vfs
  BUILDAH_FORMAT: docker
  DOCKER_DRIVER: overlay2

build-al9:
  image: $CI_REGISTRY/ndmspc/user/al9:dep
  stage: build
  tags:
    - ndmspc-hosted
  script: scripts/make.sh release test
  except:
    - main
    - tags

build-al10:
  image: $CI_REGISTRY/ndmspc/user/al10:dep
  stage: build
  tags:
    - ndmspc-hosted
  script: scripts/make.sh release test
  allow_failure: true
  except:
    - main
    - tags

build-rpm-copr:
  stage: deploy
  tags:
    - ndmspc-hosted
  image:
    name: $CI_REGISTRY/ndmspc/user/al9:dep
  script:
    - export COPR_LOGIN COPR_TOKEN COPR_USER
    - scripts/copr.sh $COPR_DEBUG
    - export MY_PROJECT_VER=${CI_COMMIT_REF_NAME/v/}
    - export MY_VER_RELEASE=$(echo $MY_PROJECT_VER | cut -sd '-' -f2)
    - scripts/make.sh rpm
    - if [ -z "$MY_VER_RELEASE" ];then copr-cli build ndmspc/stable build/SRPMS/*.src.rpm --nowait; fi
    - if [ -n "$MY_VER_RELEASE" ];then copr-cli build ndmspc/testing build/SRPMS/*.src.rpm --nowait; fi
  only:
    - tags

prod-image:
  stage: deploy
  tags:
    - images
  script:
    - podman login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - podman pull $CI_REGISTRY_IMAGE:latest || true
    - export MY_PROJECT_VER=${CI_COMMIT_REF_NAME/v/}
    - export MY_VER_RELEASE=$(echo $MY_PROJECT_VER | cut -sd '-' -f2)
    - podman build --build-arg MY_PROJECT_VER="$MY_PROJECT_VER" --cache-from $CI_REGISTRY_IMAGE:latest --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME --tag $CI_REGISTRY_IMAGE:latest --tag $CI_REGISTRY_IMAGE:next .
    - podman push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
    # - if [ "$CI_COMMIT_REF_NAME" == "main" ]; then docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA; fi
    - if [ -z "$MY_VER_RELEASE" ];then podman push $CI_REGISTRY_IMAGE:latest; fi
    - if [ -n "$MY_VER_RELEASE" ];then podman push $CI_REGISTRY_IMAGE:next; fi
  allow_failure: true
  # when: manual
  only:
    - tags
    # - main
pages:
  image: registry.gitlab.com/ndmspc/user/fc43:dep
  stage: deploy
  tags:
    - ndmspc-hosted
  script:
    - scripts/make.sh doc install
    - mv share/doc/ndmspc/html public
  artifacts:
    paths:
      - public
  only:
    - main
