stages:
  - build
  - deploy

build-al9:
  image: $CI_REGISTRY/ndmspc/user/al9:dep
  stage: build
  script: scripts/make.sh release
  except:
    - main
    - tags

build-rpm-copr:
  stage: deploy
  image:
    name: $CI_REGISTRY/ndmspc/user/al9:dep
  script:
    - export COPR_LOGIN COPR_TOKEN COPR_USER
    - scripts/copr.sh $COPR_DEBUG
    - export MY_PROJECT_VER=${CI_COMMIT_REF_NAME/v/}
    - export MY_VER_RELEASE=$(echo $MY_PROJECT_VER | cut -sd '-' -f2)
    - scripts/make.sh rpm
    - if [ -z "$MY_VER_RELEASE" ];then copr-cli build ndmspc/stable build/SRPMS/*.src.rpm --nowait; fi
    - if [ -n "$MY_VER_RELEASE" ];then copr-cli build ndmspc/testing build/SRPMS/*.src.rpm --nowait; fi
  only:
    - tags
